#!/usr/bin/env python3
"""
rss_probe.py  --  discover which RSS feeds actually work, for the EXECUTIVE map wire.

It probes two sets and prints a ready-to-paste WORKING list:
  1) the current curated WIRE_FEEDS, and
  2) common feed paths guessed from this map's own news-type sources
     (investigative-journalism / blog / podcast / video trackers).

A feed "works" if feedparser returns >=3 dated entries. Paste the WORKING
block into wire_harvest.py's FEEDS list (and into the map's WIRE_FEEDS).

No API key. Requires: feedparser  (pip install feedparser)

    python3 rss_probe.py                 # probe all, print working + dead
    python3 rss_probe.py > feeds_ok.txt  # save the working list
"""
import sys, re
from urllib.parse import urlsplit
try:
    import feedparser
except ImportError:
    sys.exit("Install feedparser first:  pip install feedparser")

CURATED = [
    ("100Reporters", "https://100r.org/feed/"),
    ("Abzas Media", "https://abzas.org/en/rss.xml"),
    ("African Network of Centers for Investigative Reporting (ANCIR)", "https://investigate.africa/feed"),
    ("Agência Pública", "https://apublica.org/feed/"),
    ("Alqatiba", "https://alqatiba.com/feed/"),
    ("amaBhungane Centre for Investigative Journalism", "https://amabhungane.org/feed/"),
    ("Arab Reporters for Investigative Journalism (ARIJ)", "http://en.arij.net/feed"),
    ("Armando.info", "https://armando.info/feed/"),
    ("atlatszo.hu", "https://atlatszo.hu/feed/"),
    ("Balkan Investigative Reporting Network (BIRN)", "https://birn.eu.com/feed/"),
    ("Bellingcat", "https://www.bellingcat.com/feed"),
    ("Bihus.info", "https://bihus.info/feed"),
    ("Bivol.bg", "https://bivol.bg/feed"),
    ("Bolts", "https://boltsmag.org/feed"),
    ("BudgIT", "https://budgit.org/feed/"),
    ("Byline Times", "https://bylinetimes.com/feed/"),
    ("CAinfo (Centro de Archivo y Acceso a la Información Pública)", "http://cainfo.org.uy/feed"),
    ("Carter Center — Election Standards", "https://electionstandards.cartercenter.org/feed/"),
    ("Center for Investigative Journalism of Montenegro (CIN-CG)", "http://www.cin-cg.me/feed"),
    ("Center for Investigative Journalism of Serbia (CINS)", "https://www.cins.rs/web-stories/feed/"),
    ("Center for Investigative Reporting (CIN)", "https://cin.ba/feed/"),
    ("Center for Investigative Reporting (Reveal)", "https://revealnews.org/feed/"),
    ("Center for Investigative Reporting, Sri Lanka", "https://cir.lk/feed/"),
    ("Center for Public Integrity", "https://publicintegrity.org/feed/"),
    ("Centre for Investigative Journalism Malawi (CIJM)", "https://www.investigative-malawi.org/feed/"),
    ("Centro de Periodismo Investigativo — Puerto Rico", "https://periodismoinvestigativo.com/feed/"),
    ("Centro Latinoamericano de Investigación Periodística (CLIP)", "https://www.elclip.org/feed/"),
    ("Chronicles.Media", "https://chronicles.media/feed/"),
    ("CIPER — Centro de Investigación Periodística", "https://www.ciperchile.cl/feed/"),
    ("Civil Discourse (Joyce Vance)", "https://joycevance.substack.com/feed"),
    ("Coda Media", "https://www.codastory.com/feed/"),
    ("Confidencial", "https://confidencial.digital/feed"),
    ("Congressional Dish (Jennifer Briney)", "https://congressionaldish.com/feed"),
    ("Connectas", "https://www.connectas.org/feed/"),
    ("Context.ro", "https://context.ro/feed/"),
    ("CONVOCA", "https://convoca.pe/rss.xml"),
    ("CORRECTIV", "https://www.correctiv.org/feed"),
    ("Crimean Center for Investigative Journalism", "http://investigator.org.ua/feed"),
    ("CU Sens", "https://cusens.md/ro/feed/"),
    ("Cyprus Investigative Reporting Network (CIReN)", "http://www.ciren.cy/feed"),
    ("Czech Centre for Investigative Journalism", "https://www.investigace.cz/feed/"),
    ("Danwatch", "https://danwatch.dk/en/feed/"),
    ("Data Cameroon", "https://datacameroon.com/feed/"),
    ("DCReport", "https://www.dcreport.org/feed/"),
    ("Declassified UK", "https://www.declassifieduk.org/feed/"),
    ("Direkt36", "http://www.direkt36.hu/en/feed"),
    ("DISCLOSE", "https://disclose.ngo/feed/?lang=en"),
    ("Drop Site News", "https://www.dropsitenews.com/feed"),
    ("El Surtidor", "https://elsurti.com/feed"),
    ("Election Law Blog (Rick Hasen)", "https://electionlawblog.org/?feed=rss2"),
    ("emptywheel (Marcy Wheeler)", "https://emptywheel.net/feed/"),
    ("Environmental Investigative Forum", "https://eiforum.org/feed/"),
    ("Epicentro.TV", "https://epicentro.tv/rss/global.xml"),
    ("Fiquem Sabendo", "https://fiquemsabendo.com.br/rss/"),
    ("Follow the Money", "https://www.ftm.eu/feed"),
    ("Forbidden Stories", "https://forbiddenstories.org/feed/"),
    ("FrontStory / Fundacja Reporterów", "https://frontstory.pl/feed/"),
    ("Fundación Ciudadana Civio", "http://www.civio.es/feed.xml"),
    ("GIJN — Global Investigative Journalism Network", "https://gijn.org/rss"),
    ("Global Reporting Center", "https://globalreportingcentre.org/feed/"),
    ("HETQ — Investigative Journalists of Armenia", "https://hetq.am/en/rss"),
    ("ICIJ — International Consortium of Investigative Journalists", "https://www.icij.org/feed"),
    ("IDL-Reporteros", "https://www.idl-reporteros.pe/feed/"),
    ("inewsource", "https://inewsource.org/feed/"),
    ("Inhlase Centre for Investigative Journalism", "https://inhlase.com/feed/"),
    ("Inkyfada", "https://inkyfada.com/fr/feed/"),
    ("InSight Crime", "https://insightcrime.org/feed/"),
    ("Instituto Prensa y Sociedad (IPYS)", "http://www.ipys.org/rss.xml"),
    ("International Centre for Investigative Reporting (ICIR)", "https://www.icirnigeria.org/feed/"),
    ("Investico", "https://www.platform-investico.nl/feed"),
    ("Investigative Center of Jan Kuciak (ICJK)", "https://www.icjk.sk/rss"),
    ("Investigative Journalism Bureau", "https://ijb.utoronto.ca/feed/"),
    ("Investigative Journalism Center of Moldova", "https://anticoruptie.md/ro/feed"),
    ("Investigative Reporting Denmark", "https://www.ir-d.dk/feed/"),
    ("Investigative Reporting Lab Macedonia", "https://irl.mk/mk/feed/"),
    ("Investigative Reporting Workshop", "http://investigativereportingworkshop.org/feed"),
    ("IStories (Important Stories)", "https://istories.media/rss/all.xml"),
    ("iWatch Africa", "http://iwatchafrica.org/feed/"),
    ("JARING", "https://jaring.id/feed/"),
    ("Just Security", "https://www.justsecurity.org/feed/"),
    ("Kloop Media", "https://kloop.kg/feed/"),
    ("KRIK — Crime and Corruption Reporting Network", "https://www.krik.rs/feed/"),
    ("La Maison des Reporters", "https://lamaisondesreporters.sn/feed/"),
    ("Lighthouse Reports", "https://www.lighthousereports.com/feed/"),
    ("LUPA — Crime and Corruption Reporting Network", "https://lupa.co.me/feed/"),
    ("Mada Masr", "https://www.madamasr.com/en/feed"),
    ("Maka Angola", "https://www.makaangola.org/feed/"),
    ("Makanday", "https://makanday.org/feed/"),
    ("Maldita.es", "https://maldita.es/feed"),
    ("MapLight", "https://www.maplight.org/blog-feed.xml"),
    ("Mexicanos Contra la Corrupción y la Impunidad (MCCI)", "https://contralacorrupcion.mx/feed/"),
    ("Midwest Center for Investigative Reporting", "https://investigatemidwest.org/feed/"),
    ("Mikroskop Media", "https://mikroskopmedia.com/feed/"),
    ("Ministério Público – Amapá", "https://www.mpap.mp.br/rss"),
    ("Ministério Público – Ceará", "https://mpce.mp.br/feed/"),
    ("Ministério Público – Maranhão", "https://www.mpma.mp.br/feed"),
    ("Ministério Público – Paraíba", "https://www.mppb.mp.br/rss"),
    ("MNN Centre for Investigative Journalism", "https://lescij.org/feed/"),
    ("MPDFT (Ministério Público)", "https://www.mpdft.mp.br/portal/index.php?format=feed&type=rss"),
    ("MUSEBA Journalism Project", "https://www.themusebaproject.org/feed/"),
    ("Nashi Groshi (“Our Money”)", "https://nashigroshi.org/feed/"),
    ("Nikolaev Center for Investigative Reporting (NikCIR)", "https://nikcenter.org/feed/"),
    ("Notes on the Crises (Nathan Tankus)", "https://www.crisesnotes.com/rss/"),
    ("OCCRP — Organized Crime & Corruption Reporting Project", "https://www.occrp.org/en/feed"),
    ("openDemocracy", "https://www.opendemocracy.net/rss/"),
    ("Ortak", "https://ortak.org/feed/"),
    ("Oxpeckers", "https://oxpeckers.org/feed/"),
    ("Oštro", "https://ostro.si/feed/"),
    ("Periodismo de Barrio", "https://periodismodebarrio.org/feed/"),
    ("Philippine Center for Investigative Journalism (PCIJ)", "https://pcij.org/feed/"),
    ("Plaza Pública", "https://plazapublica.com.gt/feed/"),
    ("Pod črto", "https://podcrto.si/feed"),
    ("Popular Information (Judd Legum)", "https://popular.info/feed"),
    ("Prachatai", "https://prachatai.com/feed"),
    ("Proekt (The Project)", "https://www.proekt.media/feed/"),
    ("ProPublica", "https://www.propublica.org/feeds/propublica/main"),
    ("Public Herald", "https://publicherald.org/feed/"),
    ("Quinto Elemento Lab", "https://quintoelab.org/feed"),
    ("Rappler / Newsbreak", "https://www.rappler.com/feed/"),
    ("Re:Baltica — Baltic Centre for Investigative Journalism", "https://rebaltica.lv/feed/"),
    ("REFLEKT", "http://reflekt.ch/api/rss-feed"),
    ("REJI-RDC", "https://www.reji-rdc.org/feed/"),
    ("Reporters United", "https://www.reportersunited.gr/feed/"),
    ("Republik", "https://www.republik.ch/feed.xml"),
    ("Repórter Brasil", "https://reporterbrasil.org.br/feed/"),
    ("RISE Moldova", "https://www.rise.md/feed/"),
    ("RISE Project", "http://www.riseproject.ro/feed"),
    ("SCOOP-Macedonia", "http://scoop.mk/feed/"),
    ("Siena", "https://www.siena.lt/blog-feed.xml"),
    ("SIRAJ — Syrian Investigative Reporting for Accountability Journalism", "https://sirajsy.net/ar/feed"),
    ("Slidstvo.info", "https://www.slidstvo.info/feed/"),
    ("Sludge", "https://readsludge.com/rss/"),
    ("Solomon", "https://wearesolomon.com/feed/"),
    ("Studio Monitor", "https://monitori.ge/feed"),
    ("Tansa — Tokyo Investigative Newsroom", "https://en.tansajp.org/rss.xml"),
    ("Temirov Live", "https://www.youtube.com/feeds/videos.xml?channel_id=UCpZtteaL03_LrVORzSfxwZg"),
    ("Texas Observer", "https://www.texasobserver.org/feed/"),
    ("Texty.org.ua — Data Journalism Agency", "http://texty.org.ua/feed.xml"),
    ("The Bristol Cable", "https://thebristolcable.org/feed"),
    ("The Centre for Climate Reporting", "https://climate-reporting.org/feed/"),
    ("The Elephant", "https://www.theelephant.info/feed/"),
    ("The Ferret", "https://www.theferret.scot/latest/rss/"),
    ("The Investigative Desk", "https://investigativedesk.com/feed/"),
    ("The Lever", "https://www.levernews.com/rss/"),
    ("The Marshall Project", "https://www.themarshallproject.org/rss/recent"),
    ("The Public Source", "https://thepublicsource.org/feed"),
    ("The Reporter (Taiwan)", "https://www.twreporter.org/a/rss2.xml"),
    ("The War Horse", "https://thewarhorse.org/feed/"),
    ("Turkmen.News", "https://turkmen.news/feed/"),
    ("Type Investigations", "https://typeinvestigations.org/feed"),
    ("Viewfinder", "https://viewfinder.org.za/feed/"),
    ("Watershed Investigations", "https://watershedinvestigations.com/feed"),
    ("Wisconsin Watch", "https://wisconsinwatch.org/feed/"),
    ("Wole Soyinka Centre for Investigative Journalism", "https://wscij.org/feed/"),
    ("Ziarul de Gardă", "https://www.zdg.md/feed"),
    ("Átlátszó Erdély", "https://atlatszo.ro/feed/")
]

# this map's own news-type sources (homepages); we guess common feed paths
MAP_NEWS = [
    ("Lawfare", "https://www.lawfaremedia.org/"),
    ("The War Horse", "https://thewarhorse.org/"),
    ("DCReport", "https://www.dcreport.org/"),
    ("Tucson Sentinel", "https://www.tucsonsentinel.com/"),
    ("Public Herald", "https://publicherald.org/"),
    ("Arnolt Center for Investigative Journalism", "https://arnoltcenter.org/"),
    ("Investigative Reporting Workshop", "https://investigativereportingworkshop.org/"),
    ("Howard Center for Investigative Journalism (ASU)", "https://howardcenter.asu.edu/"),
    ("100Reporters", "https://100r.org/"),
    ("Investigate Midwest", "https://investigatemidwest.org/"),
    ("inewsource", "https://inewsource.org/"),
    ("Type Investigations", "https://typeinvestigations.org/"),
    ("Center for Public Integrity", "https://www.publicintegrity.org/"),
    ("The Marshall Project", "https://www.themarshallproject.org/"),
    ("Reveal (Center for Investigative Reporting)", "https://revealnews.org/"),
    ("ProPublica", "https://www.propublica.org/"),
    ("Canadaland", "https://www.canadaland.com/"),
    ("The Narwhal", "https://thenarwhal.ca/"),
    ("Investigative Journalism Bureau", "https://ijb.utoronto.ca/"),
    ("La Silla Vacía", "https://www.lasillavacia.com/"),
    ("Chequeado", "https://chequeado.com/"),
    ("CIPER (Centro de Investigación Periodística)", "https://www.ciperchile.cl/"),
    ("Repórter Brasil", "https://reporterbrasil.org.br/"),
    ("Agência Pública", "https://apublica.org/"),
    ("Quinto Elemento Lab", "https://quintoelab.org/"),
    ("Plaza Pública", "https://plazapublica.com.gt/"),
    ("Plaza Pública", "https://www.plazapublica.com.gt/"),
    ("GK (GKillCity)", "https://gk.city/"),
    ("IDL-Reporteros", "https://idl-reporteros.pe/"),
    ("Epicentro.TV", "https://epicentro.tv/"),
    ("CONVOCA", "https://convoca.pe/"),
    ("OjoPúblico", "https://ojo-publico.com/"),
    ("Contracorriente", "https://contracorriente.red/"),
    ("El Pitazo", "https://elpitazo.net/"),
    ("Armando.info", "https://armando.info/"),
    ("Byline Times", "https://bylinetimes.com/"),
    ("openDemocracy", "https://www.opendemocracy.net/"),
    ("The Bureau of Investigative Journalism (TBIJ)", "https://www.thebureauinvestigates.com/"),
    ("The Bristol Cable", "https://thebristolcable.org/"),
    ("The Ferret", "https://theferret.scot/"),
    ("The Gecko Project", "https://thegeckoproject.org/"),
    ("CORRECTIV", "https://correctiv.org/"),
    ("Mediapart", "https://www.mediapart.fr/"),
    ("Disclose", "https://disclose.ngo/en"),
    ("IRPI / IrpiMedia (Investigative Reporting Project Italy)", "https://irpi.eu/"),
    ("Reporters United", "https://www.reportersunited.gr/"),
    ("Solomon", "https://wearesolomon.com/"),
    ("investigace.cz (Czech Centre for Investigative Journalism)", "https://www.investigace.cz/"),
    ("DOSSIER", "https://www.dossier.at/"),
    ("Onderzoekscollectief SPIT", "https://www.onderzoekscollectiefspit.nl/"),
    ("Investico", "https://www.platform-investico.nl/"),
    ("ZAM", "https://www.zammagazine.com/"),
    ("Lighthouse Reports", "https://www.lighthousereports.nl/"),
    ("The Investigative Desk", "https://www.investigativedesk.com/"),
    ("Follow the Money", "https://www.ftm.nl/"),
    ("Investigative Reporting Denmark", "https://www.ir-d.dk/"),
    ("Danwatch", "https://danwatch.dk/en/"),
    ("FRONTSTORY.PL (Fundacja Reporterów)", "https://frontstory.pl/"),
    ("Context Investigations", "https://context.ro/"),
    ("RISE Project", "https://www.riseproject.ro/"),
    ("Átlátszó Erdély", "https://atlatszo.ro/"),
    ("KRIK", "https://www.krik.rs/"),
    ("Center for Investigative Journalism of Serbia (CINS)", "https://www.cins.rs/"),
    ("Slidstvo.info", "https://slidstvo.info/"),
    ("NGL.media", "https://ngl.media/"),
    ("NIKCENTER (Mykolaiv Center for Investigative Reporting)", "https://nikcenter.org/"),
    ("Fourth Estate (4vlada)", "https://4vlada.com/"),
    ("Nashi Groshi (Our Money)", "https://nashigroshi.org/"),
    ("Texty.org.ua", "https://texty.org.ua/"),
    ("Bihus.info", "https://bihus.info/"),
    ("Crimean Center for Investigative Journalism", "https://investigator.org.ua/"),
    ("Direkt36", "https://www.direkt36.hu/"),
    ("Átlátszó (atlatszo.hu)", "https://atlatszo.hu/"),
    ("Direkt36", "https://www.direkt36.hu/en/"),
    ("Investigative Center of Ján Kuciak (ICJK)", "https://www.icjk.sk/"),
    ("Studio Monitor", "https://monitori.ge/"),
    ("Ziarul de Gardă", "https://www.zdg.md/"),
    ("RISE Moldova", "https://www.rise.md/"),
    ("Investigative Journalism Center of Moldova (anticoruptie.md)", "https://anticoruptie.md/"),
    ("CU Sens", "https://cusens.md/ro/"),
    ("Center for Investigative Reporting (CIN)", "https://www.cin.ba/"),
    ("SCOOP-Macedonia", "https://www.scoop.mk/"),
    ("Investigative Reporting Lab (IRL) Macedonia", "https://irl.mk/"),
    ("LUPA (Crime and Corruption Reporting Network)", "https://lupa.co.me/"),
    ("Center for Investigative Journalism of Montenegro (CIN-CG)", "https://www.cin-cg.me/"),
    ("Africa Uncensored", "https://africauncensored.online/"),
    ("amaBhungane Centre for Investigative Journalism", "https://amabhungane.org/"),
    ("Viewfinder", "https://viewfinder.org.za/"),
    ("The Fourth Estate (MFWA)", "https://thefourthestategh.com/"),
    ("Premium Times", "https://www.premiumtimesng.com/"),
    ("Wole Soyinka Centre for Investigative Journalism", "https://wscij.org/"),
    ("International Centre for Investigative Reporting (ICIR)", "https://icirnigeria.org/"),
    ("Alqatiba", "https://alqatiba.com/"),
    ("Inkyfada", "https://inkyfada.com/"),
    ("Le Desk", "https://ledesk.ma/"),
    ("The Observer", "https://observer.ug/"),
    ("The Chanzo", "https://thechanzo.com/"),
    ("7iber (حبر)", "https://www.7iber.com/"),
    ("The Public Source", "https://thepublicsource.org/"),
    ("IndiaSpend", "https://www.indiaspend.com/"),
    ("Cobrapost", "https://www.cobrapost.com/"),
    ("The Reporters' Collective", "https://www.reporters-collective.in/"),
    ("Malaysiakini", "https://www.malaysiakini.com/"),
    ("Tansa (Tokyo Investigative Newsroom)", "https://en.tansajp.org/"),
    ("Newstapa (Korea Center for Investigative Journalism)", "https://www.newstapa.org/"),
    ("The Reporter (Taiwan)", "https://www.twreporter.org/"),
    ("Rappler", "https://www.rappler.com/"),
    ("VERA Files", "https://verafiles.org/"),
    ("Newsbreak (Rappler)", "https://www.rappler.com/newsbreak/"),
    ("Philippine Center for Investigative Journalism (PCIJ)", "https://pcij.org/"),
    ("Hetq (Investigative Journalists of Armenia)", "https://hetq.am/en/"),
    ("Michael West Media", "https://michaelwest.com.au/"),
    ("Oštro", "https://www.portal-ostro.hr/"),
    ("Investigative Journalism Center (Croatia)", "https://cin-ijc.eu/"),
    ("Republik", "https://www.republik.ch/"),
    ("Reflekt", "https://reflekt.ch/"),
    ("Bivol", "https://bivol.bg/"),
    ("Re:Baltica — Baltic Centre for Investigative Journalism", "https://en.rebaltica.lv/"),
    ("Re:Baltica (Baltic Centre for Investigative Journalism)", "https://rebaltica.lv/en/"),
    ("Siena", "https://siena.lt/"),
    ("Oštro Slovenia", "https://www.ostro.si/"),
    ("Pod črto", "https://podcrto.si/"),
    ("Cyprus Investigative Reporting Network (CIReN)", "https://www.ciren.cy/"),
    ("Center for Investigative Reporting (Sri Lanka)", "https://cir.lk/"),
    ("Netra News", "https://netra.news/"),
    ("Prachatai", "https://prachatai.com/"),
    ("JARING", "https://www.jaring.id/"),
    ("El Faro", "https://elfaro.net/"),
    ("El Surtidor", "https://elsurti.com/"),
    ("News Diggers!", "https://diggers.news/"),
    ("Makanday Centre for Investigative Journalism", "https://makanday.org/"),
    ("Mada Masr", "https://www.madamasr.com/en/"),
    ("OuestAf", "https://www.ouestaf.com/"),
    ("La Maison des Reporters", "https://lamaisondesreporters.sn/"),
    ("The Chronicles", "https://www.chronicles.rw/"),
    ("Addis Standard", "https://addisstandard.com/"),
    ("The Fiji Times", "https://www.fijitimes.com.fj/"),
    ("Inside PNG", "https://insidepng.com/"),
    ("Ortak", "https://ortak.org/"),
    ("Meduza", "https://meduza.io/en"),
    ("Chronicles.Media", "https://chronicles.media/"),
    ("Proekt (The Project)", "https://www.proekt.media/"),
    ("iStories (Important Stories)", "https://istories.media/en/"),
    ("Zerkalo", "https://zerkalo.io/"),
    ("Buro Media", "https://buromedia.io/en/"),
    ("Belarusian Investigative Center", "https://investigatebel.org/en/"),
    ("Mikroskop Media", "https://mikroskopmedia.com/"),
    ("Abzas Media", "https://abzas.org/en/"),
    ("Maldives Independent", "https://maldivesindependent.com/"),
    ("Vlast", "https://vlast.kz/"),
    ("Temirov Live", "https://www.youtube.com/@TemirovLIVE"),
    ("Kloop", "https://kloop.kg/"),
    ("Center for Investigative Journalism, Nepal", "https://cijnepal.org.np/"),
    ("CamboJA News", "https://cambojanews.com/"),
    ("The NewsHawks", "https://thenewshawks.com/"),
    ("Centre for Investigative Journalism Malawi", "https://www.investigative-malawi.org/"),
    ("Platform for Investigative Journalism (PIJ) Malawi", "https://www.pijmalawi.org/"),
    ("Zitamar News", "https://www.zitamar.com/"),
    ("Actualité.cd", "https://actualite.cd/"),
    ("Radio Tamazuj", "https://www.radiotamazuj.org/en"),
    ("AyiboPost", "https://ayibopost.com/"),
    ("Vanuatu Daily Post", "https://www.dailypost.vu/"),
    ("In-depth Solomons", "https://indepthsolomons.com.sb/"),
    ("14ymedio", "https://www.14ymedio.com/"),
    ("Confidencial", "https://confidencial.digital/"),
    ("IranWire", "https://iranwire.com/en/"),
    ("Data Cameroon", "https://datacameroon.com/"),
    ("The Museba Project", "https://www.themusebaproject.org/"),
    ("The Vietnamese Magazine", "https://thevietnamese.org/"),
    ("Maka Angola", "https://www.makaangola.org/en/"),
    ("Maka Angola", "https://www.makaangola.org/"),
    ("Iwacu", "https://www.iwacu-burundi.org/"),
    ("MNN Centre for Investigative Journalism", "https://lescij.org/"),
    ("Garowe Online", "https://www.garoweonline.com/en"),
    ("Ayin Network", "https://3ayin.com/en/"),
    ("Swaziland News", "https://swazilandnews.co.za/"),
    ("Inhlase Centre for Investigative Journalism", "https://inhlase.com/"),
    ("Al-Masdar Online", "https://al-masdaronline.net/"),
    ("Myanmar Now", "https://myanmar-now.org/en/"),
    ("Hasht-e Subh (8am)", "https://8am.media/eng/"),
    ("Gazeta.uz", "https://www.gazeta.uz/"),
    ("Asia-Plus", "https://asiaplustj.info/en"),
    ("turkmen.news", "https://en.turkmen.news/"),
    ("Turkmen.News", "https://turkmen.news/"),
    ("Eritrea Hub", "https://eritreahub.org/"),
    ("Daily NK", "https://www.dailynk.com/english/"),
    ("Diario Rombe", "https://diariorombe.es/"),
    ("Enab Baladi", "https://english.enabbaladi.net/")
]
GUESS_PATHS = ["/feed/", "/feed", "/rss", "/rss.xml", "/feed.xml", "/atom.xml",
               "/index.xml", "/feeds/all.rss", "/en/feed/", "/feed/rss/"]

def works(url):
    try:
        d = feedparser.parse(url)
        good = [e for e in d.entries if e.get("published_parsed") or e.get("updated_parsed")]
        return len(good) >= 3
    except Exception:
        return False

def probe(pairs):
    ok, dead = [], []
    for name, url in pairs:
        if works(url): ok.append((name, url)); print("  ok   %-28s %s" % (name, url))
        else:          dead.append((name, url)); print("  DEAD %-28s %s" % (name, url))
    return ok, dead

def guess_from_homepages(pairs):
    found = []
    seen = set()
    for name, url in pairs:
        base = "%s://%s" % (urlsplit(url).scheme or "https", urlsplit(url).netloc)
        if not base or base in seen: continue
        seen.add(base)
        for p in GUESS_PATHS:
            cand = base + p
            if works(cand):
                found.append((name, cand)); print("  FOUND %-26s %s" % (name, cand)); break
    return found

if __name__ == "__main__":
    print("== Probing curated WIRE_FEEDS ==")
    ok1, dead1 = probe(CURATED)
    print("\n== Guessing feeds from this map's news sources ==")
    ok2 = guess_from_homepages(MAP_NEWS)
    working = {u:(n,u) for n,u in (ok1+ok2)}.values()
    print("\n\n===== WORKING FEEDS (paste into wire_harvest.py FEEDS) =====")
    for n,u in sorted(working):
        print('    ("%s", "%s"),' % (n.replace('"',chr(92)+chr(34)), u))
    print("\n# %d working, %d dead in curated set." % (len(ok1), len(dead1)))
